### ISSUE TITLE
Install lacking 'DAP' button

### ISSUE THREAD

**Issue by alastc** [IBMa/AAT#1]
Hi,

I was trying out the Dynamic Assessment Plugin Chrome pluggin, following the instructions under the Tools tab, and got stuck on:

> The Elements panel should automatically open. In the bottom section, select DAP on the far right.

I assume this is in the same bunch of panels you get when you 'inspect' a page, but there is no DAP button there.

I have the red DAP icon in the main chrome window, which has options/support/help, but nothing in the inspector.

Any ideas for progressing?

Kind regards,

-Alastair

**Comment by carmacleod** [comment]
Is there, by any chance, a chevron (>>) in the list of panels? If so, try clicking on that.
(This can happen if you have a bunch of plugins that provide panels).

**Comment by alastc** [comment]
No, I widened the window. I have the standard set, then audits, then chromelens, then a big blank area before the console errors and docking control on the right.

**Comment by alastc** [comment]
Ah, found it! Sorry, I thought it was a top panel, but it appears with the styles/computed/events listeners set on the right hand side. It might be worth updating the intro to specify that, I was used to pluggins adding top-level panels rather than the properties one.

**Comment by carmacleod** [comment]
You are right. I think the following sentence is the misleading one:

>  In the bottom section, select DAP on the far right.

It must have been written by someone who had the devtools docked on the right. I think it should be more generically rewritten to something like:

>  In the Elements subpanels, select the DAP panel on the far right.

@moekraft Do you know who can update the public DAP Tools (install/startup instructions) page?
https://aat.mybluemix.net/auth/tools/dap.html
