### ISSUE TITLE
Supported Rulesets do not appear to be current

### ISSUE THREAD

**Issue by johnholtman** [IBMa/AAT#11]
After installing the DAP extension and applying the token copied from this page:
https://aat.w3ibm.mybluemix.net/
I see only these two choices under Supported Rulesets:
 - IBM_Accessibility_2017_02.name
 - IBM Accessibility BETA

I would expect the Supported Rulesets to match those shown on this page:
https://aat.w3ibm.mybluemix.net/auth/rules.html

**Comment by asghar3** [comment]
User was directed to internal links. User error.
Closing.
