### ISSUE TITLE
Request to update instructions

### ISSUE THREAD

**Issue by moekraft** [IBMa/AAT#2]
From Carolyn Macleod's feedback to issue #1.
You are right. I think the following sentence is the misleading one:

In the bottom section, select DAP on the far right.
It must have been written by someone who had the devtools docked on the right. I think it should be more generically rewritten to something like:

In the Elements subpanels, select the DAP panel on the far right.
@moekraft Do you know who can update the public DAP Tools (install/startup instructions) page?
https://aat.mybluemix.net/auth/tools/dap.html

**Comment by asghar3** [comment]
@moekraft Is still an issue. The instructions were updated while back.

**Comment by asghar3** [comment]
Closing. We can touch base on this internally - if needed.
